name: Deploy to Surge

on:
  push:
    branches:
      - '*'
      - '**'
    tags:
      - '*'
      - '**'

  pull_request:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./
    shell: bash

env:
  domain: learnery.surge.sh

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: surge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 20

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Extract Domain
        id: extract_domain
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            pr_number="${{ github.event.pull_request.number }}"
            domain="pr-$pr_number-${{ env.domain }}"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/(.*)$ ]]; then
            tag_version=$(echo "${{ github.ref }}" | sed -e "s/^refs\/tags\/v//")
            domain="tag-$tag_version-${{ env.domain }}"
          else
            ref=$(git rev-parse --abbrev-ref HEAD)
            sref=${ref//\//-}
            domain="$sref-${{ env.domain }}"
          fi
          echo "preview_domain=$domain" >> $GITHUB_ENV
                
      - name: Get working directory
        id: wkdir
        run: |
          echo "wkdir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Preview to ${{ steps.extract_domain.outputs.preview_domain }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ steps.extract_domain.outputs.preview_domain }}
          project: ${{ steps.wkdir.outputs.wkdir }}/build
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Deploy to ${env.domain}
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${env.domain}
          project: ${{ steps.wkdir.outputs.wkdir }}/build
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
